name: Publish Python Package

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy:
    # Only run if the closed pull request was merged, and didn't contain the `skip-release` tag
    if: ${{ (github.event.pull_request.merged == true) && (!contains(github.event.pull_request.labels.*.name, 'skip-release')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build and publish to PyPI
        run: poetry publish --build -u __token__ -p $PYPI_API_TOKEN
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
