name: Run Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lock-file-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Check poetry lock file
        run: poetry lock --check
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        toxenv: [test]
        include:
          - python-version: "3.10"
            toxenv: lint
          - python-version: "3.10"
            toxenv: typing
          - python-version: "3.10"
            toxenv: codespell
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}
